org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.2
helm_version=0.0.5
maven_group=dev.helm
archives_base_name=HELM

loader_version=0.19.3
fabric_api_version=0.161.0+26.2
loom_version=1.18.2
mixin_version=0.8.7
fastutil_version=8.5.18

java_version=25

fabric.loom.disableObfuscation=true
